# Generated by Django 5.0 on 2024-07-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='quizzes_taken',
            field=models.IntegerField(default=0),
        ),
    ]
