# Generated by Django 5.0 on 2024-07-27 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_birdphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='birdphoto',
            name='isPrimary',
            field=models.BooleanField(default=False),
        ),
    ]
