# Generated by Django 5.0 on 2024-07-27 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_birdphoto_isprimary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BirdPhoto',
        ),
    ]
