# Generated by Django 5.0 on 2024-07-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_birdphoto_isprimary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birdphoto',
            name='photo',
            field=models.ImageField(upload_to='bird_photos'),
        ),
    ]
