# Generated by Django 5.0 on 2024-07-27 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_birdphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirdPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='bird-images/')),
                ('url', models.URLField()),
                ('photographer', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=50)),
                ('isPrimary', models.BooleanField(default=False)),
                ('license', models.CharField(choices=[('Pexels', 'Pexels License')], max_length=50)),
                ('bird', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bird')),
            ],
        ),
    ]
