# Generated by Django 5.0 on 2024-07-30 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_birdphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to='achievements/')),
                ('requirement_stat', models.CharField(choices=[('quizzes_taken', 'Quizzes Taken'), ('quizzes_correct', 'Quizzes Correct'), ('birds_seen', 'Birds Seen')], default='quizzes_taken', max_length=50)),
                ('requirement_goal', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='birdphoto',
            name='license',
            field=models.CharField(choices=[('Pexels', 'Pexels License'), ('CC0', 'CC0 License')], max_length=50),
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
